.MODEL SMALL
.STACK 100H
.CODE

MAIN PROC
        
    MOV AH,1    ;INPUT COMMAND
    INT 21H     ;INPUT INTERRUPT
    MOV BL,AL   ;STORE INPUT IN BL      
           
    MOV AH,2    ;OUTPUT COMMAND
    MOV DL,0AH  ;NEW LINE IN DL
    INT 21H     ;OUTPUT INTERRUPT
    MOV DL,0DH  ;CRET IN DL
    INT 21H
    
    MOV AH,2
    MOV DL,BL   ;INPUT CHARACTER IN DL
    INT 21H
    
    EXIT:
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN